name: Build all supported machines and attach to output
on:
    push:
        branches:
            - v1.5.0-maint

jobs:
    # LINUX AMD64 BUILDS
    MACHINE_AW_6DOF:
        uses: ./.github/workflows/machine-build-linux-amd64.yml
        with:
            machine: MACHINE_AW_6DOF
            version: ${GITHUB_REF#refs/tags/v}
        secrets: inherit

