name: Pre-Release Build and Deploy

on:
  push:
    branches:
      - machine-*

jobs:
  linux-amd64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          token: ${{ secrets.GH_PAT }}
          submodules: true

      - name: Compile
        uses: ./.ci/rpi # Dockerfile

      - name: Copy binary
        run: mkdir /tmp/gbem && cp ./GBEM /tmp/gbem

      - name: Attach artifact to build
        uses: actions/upload-artifact@v2
        with:
          name: gbem
          path: /tmp/gbem/GBEM

