name: Build machine of type

on:
  workflow_call:
    inputs:
      machine:
        # what machine are we building (ends up in machine.txt)
        required: true
        type: string
      version:
        # version to bake into the build
        required: true
        type: string

jobs:
  rpi_machine_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          token: ${{ secrets.GH_PAT }}
          submodules: true

      - name: Set machine
        run: echo ${{ inputs.machine }} > machine.txt

      - name: Compile
        uses: ./.ci/rpi # Dockerfile

      - name: Copy binary
        run: mkdir /tmp/gbem/${{ inputs.machine }} && cp ./GBEM /tmp/gbem/${{ inputs.machine }}
