name: Build machine of type

on:
  workflow_call:
    inputs:
      machine:
        # what machine are we building (ends up in machine.txt)
        required: true
        type: string
      sub_machine:
        # what sub-machine are we building (ends up in machine.txt)
        required: false
        type: string
      version:
        # version to bake into the build
        required: true
        type: string

jobs:
  rpi_machine_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          token: ${{ secrets.GH_PAT }}
          submodules: true

      - name: Set machine
        run: echo "MAP_MACHINE ${{ inputs.machine }}" > machine.txt && echo "MAP_SUB_MACHINE ${{ inputs.sub_machine }}" >> machine.txt

      - name: Set GBC_VERSION
        run: echo "GBC_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Compile
        uses: ./.ci/rpi # Dockerfile

      - name: Copy binary
        run: mkdir -p /tmp/gbem/${{ inputs.machine }} && cp ./GBEM /tmp/gbem/${{ inputs.machine }}

      - name: Attach artifact to build
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.machine }}-rpi
          path: /tmp/gbem/${{ inputs.machine }}
