name: Build all supported machines and attach to output
on:
    push:
        branches:
            - machine-aw_j17

jobs:
    MACHINE_AW_6DOF:
        uses: ./.github/workflows/machine-build.yml
        with:
            machine: ${GITHUB_JOB}
            version: ${GITHUB_REF#refs/tags/v}
        secrets: inherit

    MACHINE_DRIVE_SPINNERS:
        uses: ./.github/workflows/machine-build.yml
        with:
            machine: ${GITHUB_JOB}
            version: ${GITHUB_REF#refs/tags/v}
        secrets: inherit
